#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn run check-format ||
(
    echo '🤢🤮🤢🤮 Its RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
# yarn run lint ||
# (
#         echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
#         false; 
# )

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... 🤔🤔🤔🤔'

echo '👷🔨👷🔨... Trying to create production build... 👷🔨👷🔨'

yarn build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

echo '🚨 Validating the branch name before pushing the code'

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|improvement|library|prerelease|release|hotfix|design)\/[a-z0-9._-]+$"

if ! echo "$local_branch" | grep -Pq "$valid_branch_regex"; then
    echo "❌🤘🔥 Uh-oh! Your branch name seems to be off-key. In this project, we groove to a specific beat: feature | bugfix | improvement | library | prerelease | release | hotfix | design. Your commit ain't jamming with our vibe. Time to remix that branch name and rock it again! 🔥🤘❌"
    exit 1
fi

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'